### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wuyish** [wardi/speedometer#1]
os:CentOS release 5.8 (Final)  Linux 2.6.18-308.16.1.el5 x86_64
and urwid-1.1.1,Speedometer 2.8
python.x86_64    2.4.3-46.el5_8.2

when  i run "speedometer -r eth0":
# speedometer -r eth0

  File "/usr/local/bin/speedometer", line 112
    n = n \* granularity + (granularity if r else 0)
                                        ^
SyntaxError: invalid syntax

**Comment by iyzsong** [comment]
Hello, old python version is unsupported, we now require python3.
Close now, thanks.
