### ISSUE TITLE
Please add proper license file

### ISSUE THREAD

**Issue by rapgro** [wardi/speedometer#10]
LGPL requests to add a valid license file (besides the unique header in sources).
You can download the official text file: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt

**Comment by wardi** [comment]
@rapgro sure, I'd accept such a pull request

**Comment by rapgro** [comment]
I'm not allowed to enforce you to use a specific license text because of legal reasons. You as the author are encouraged to distribute the official text file to comply with.
