### ISSUE TITLE
Should I bother trying to run speedometer on FreeBSD ?

### ISSUE THREAD

**Issue by rsyncnet** [wardi/speedometer#13]
After installing urwid, attempts to run speedometer yield:

IOError: [Errno 2] No such file or directory: '/proc/net/dev'

I suspect there is not an easy workaround for that but thought I would ask ...

Thank you.

**Comment by wardi** [comment]
You'll need to contribute a patch to support FreeBSD, it shouldn't be a big change if you know where to get the same byte counts per-network-interface.

**Comment by iyzsong** [comment]
Should be supported now, since speedometer now using `psutil`, feel free to reopen this if it dosen't...
