### ISSUE TITLE
Support pipe input

### ISSUE THREAD

**Issue by normanr** [wardi/speedometer#6]
This could be used to graph output of "tcpdump -w", possibly an easy way to implement network traffic filters.

**Comment by eMPee584** [comment]
This would still be a very, very nice feature. I had a look at the source, and if I was a better coder (like you are, @wardi :grinning: ) it would be a matter of maybe five minutes.

**Comment by normanr** [comment]
I actually wrote the code for this last year.  Let me see if I can find it to upload and file a pull request.

**Comment by eMPee584** [comment]
It would still be great to have speedometer support stdin measurement...

**Comment by eMPee584** [comment]
@normanr PING ; )

**Comment by kenduest** [comment]
I have fork working version, read data from standard input or pipe is available now. 

[https://github.com/kenduest/speedometer/tree/develop](url)

**Comment by kenduest** [comment]
@eMPee584 I made some code modifications to support stdin measurement, including running external shell command's stdout measurement.

Usage:

$ cat /dev/urandom | speedometer 

$ speedometer < /dev/urandom

$ curl --output - https://download.site/file.iso 2>/dev/null | speedometer

$ speedometer -d "curl https://download.site/file.iso --output -"

$ speedometer -d "cat /dev/urandom"

Available on here:

[https://github.com/kenduest/speedometer/tree/develop](https://github.com/kenduest/speedometer/tree/develop)

Any improvements and suggestions are very welcome.

**Comment by iyzsong** [comment]
@kenduest Your changes have been merged, thank you!
