### ISSUE TITLE
Question about bandwidth measurements

### ISSUE THREAD

**Issue by brentfredericksmith** [wardi/speedometer#9]
I am wondering where it gets its stats from? I ran speedtests on interfaces and it did not seem to measure correctly. Are there any limitations such as only measuring IPv4 traffic?

I am attempting to use on my Debian based Ubiquiti EdgeRouter X.

**Comment by iyzsong** [comment]
It now use the `psutil` library, which reports network interface bandwidth:
https://psutil.readthedocs.io/en/latest/index.html?highlight=net_io#psutil.net_io_counters

Close now...
